project:
  type: website
  preview:
    browser: true
  
  website:
    title: "BEM2031 materials for 2023/24"
    author: "Alison Harper"
    favicon: "images/welcome.png"
    navbar:
      logo: "images/welcome.png"
      left:
        - text: Lecture Slides
          href: Weekly_lectures/L1.qmd

format:
  html:
    theme: cosmo
    toc: true

